### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 4308) exited unexpectedly

### ISSUE THREAD

**Issue by deadworldisee** [JaidedAI/EasyOCR#1028]
I get this error and don't know what is causing it
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\FireAngelEmpire\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\FireAngelEmpire\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\FireAngelEmpire\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\FireAngelEmpire\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\FireAngelEmpire\anaconda3\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\FireAngelEmpire\anaconda3\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\FireAngelEmpire\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\situri\EasyOCRtrainer\trainer\main.py", line 37, in <module>
    train(opt, amp=False)
  File "D:\situri\EasyOCRtrainer\trainer\train.py", line 40, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "D:\situri\EasyOCRtrainer\trainer\dataset.py", line 83, in __init__
    self.dataloader_iter_list.append(iter(_data_loader))
  File "C:\Users\FireAngelEmpire\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "C:\Users\FireAngelEmpire\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\FireAngelEmpire\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1042, in __init__
    w.start()
  File "C:\Users\FireAngelEmpire\anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\FireAngelEmpire\anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\FireAngelEmpire\anaconda3\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\FireAngelEmpire\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\FireAngelEmpire\anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\FireAngelEmpire\anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Users\FireAngelEmpire\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\FireAngelEmpire\anaconda3\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\situri\EasyOCRtrainer\trainer\main.py", line 37, in <module>
    train(opt, amp=False)
  File "D:\situri\EasyOCRtrainer\trainer\train.py", line 203, in train
    image_tensors, labels = train_dataset.get_batch()
  File "D:\situri\EasyOCRtrainer\trainer\dataset.py", line 101, in get_batch
    image, text = next(data_loader_iter)
  File "C:\Users\FireAngelEmpire\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\Users\FireAngelEmpire\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "C:\Users\FireAngelEmpire\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\FireAngelEmpire\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1145, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 4308) exited unexpectedly

I use default en_filtered_config.yaml settings

**Comment by vincedani** [comment]
Hi @deadworldisee 👋 

Have you resolved the issue? I have just run into the same thing and couldn't find a solution better than `num_workers = 0`. But that's not the best from performance point of view.
