### ISSUE TITLE
error while start

### ISSUE THREAD

**Issue by Luky12568** [JaidedAI/EasyOCR#1071]
Traceback (most recent call last):
  File "c:\users\42072\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\42072\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\42072\AppData\Local\Programs\Python\Python36\Scripts\easyocr.exe\__main__.py", line 7, in <module>
  File "c:\users\42072\appdata\local\programs\python\python36\lib\site-packages\easyocr\cli.py", line 252, in main
    quantize=args.quantize)
  File "c:\users\42072\appdata\local\programs\python\python36\lib\site-packages\easyocr\easyocr.py", line 75, in __init__
    elif torch.backends.mps.is_available():
AttributeError: module 'torch.backends' has no attribute 'mps'

**Comment by YLONl** [comment]
\easyocr\easyocr.py", line 75, 


        if gpu is False:
            self.device = 'cpu'
            if verbose:
                LOGGER.warning('Using CPU. Note: This module is much faster with a GPU.')
        elif gpu is True:
            if torch.cuda.is_available():
                self.device = 'cuda'
            # elif torch.backends.mps.is_available():
            #     self.device = 'mps'
            else:
                self.device = 'cpu'
                if verbose:
                    LOGGER.warning('Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.')
        else:
            self.device = gpu
