### ISSUE TITLE
cv2.error: OpenCV(4.8.1) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by connorourke** [JaidedAI/EasyOCR#1165]
I am getting the following error when training the craft detection model using the ICDAR MLT 2017 dataset

It goes through 460/25000 training steps and then this happens. 

The '_src.empty()' error would seem to suggest that the image is empty, but it isnt, so I'm wondering if it is down to the invalid value in the scalar divide that is leaving the image empty. 

```
/mainfs/scratch/co1f23/EasyOCR/trainer/craft/data/boxEnlarge.py:56: RuntimeWarning: invalid value encountered in scalar divide
  X = (B2 - B1)/(K1 - K2)
Traceback (most recent call last):
  File "train.py", line 479, in <module>
    main()
  File "train.py", line 472, in main
    trainer.train(buffer_dict)
  File "train.py", line 239, in train
    for (
  File "/scratch/co1f23/conda/envs/easyOCR/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/scratch/co1f23/conda/envs/easyOCR/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/scratch/co1f23/conda/envs/easyOCR/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]    
data = [self.dataset[idx] for idx in possibly_batched_index]  File "/scratch/co1f23/conda/envs/easyOCR/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]  File "/mainfs/scratch/co1f23/EasyOCR/trainer/craft/data/dataset.py", line 150, in __getitem__
    ) = self.make_gt_score(index)  File "/mainfs/scratch/co1f23/EasyOCR/trainer/craft/data/dataset.py", line 457, in make_gt_score
    ) = self.load_data(index)
  File "/mainfs/scratch/co1f23/EasyOCR/trainer/craft/data/dataset.py", line 392, in load_data
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.8.1) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

Has anyone come across this error and know what the issue/fix is?

Thanks

**Comment by cgm814** [comment]
Hello, have you solved this problem? Can you tell me the solution?
