### ISSUE TITLE
How do I load the directory where the model is stored

### ISSUE THREAD

**Issue by yumianhuli1** [JaidedAI/EasyOCR#1196]
How do I use reader = easyocr.Reader(['ch_sim'], gpu=True) and load the local specified directory where the recognition network model is stored ,thank you!

**Comment by vamshi-1611** [comment]
Hello yumianhhuli
You can check in https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md
Once your model is trained keep in ~/.EasyOCR/model
You can use as reader = easyocr.Reader(['ch_sim'], recog_network=your_model_name ,gpu=True) 
In my case root is my default folder so my path will be as 
/root/.EasyOCR/model/MyModelName

**Comment by MaJoRX0** [comment]
isnt there a way 

> Hello yumianhhuli You can check in https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md Once your model is trained keep in ~/.EasyOCR/model You can use as reader = easyocr.Reader(['ch_sim'], recog_network=your_model_name ,gpu=True) In my case root is my default folder so my path will be as /root/.EasyOCR/model/MyModelName

isn't there a way to set the path to a different path than the easyocr/model?

**Comment by rinaldomerlo** [comment]
even if you try, easyocr seems to ignore it anyway. Despite using this in my script:

`reader = easyocr.Reader(['en'], model_storage_directory='/var/www/html/ocr/model')`

the optional parameter seems to be ignored and it uses the default ~/.EasyOCR/model anyway:

`==> /var/log/apache2/error.log <==
Traceback (most recent call last):
  File "/usr/lib/python3.11/pathlib.py", line 1117, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/.EasyOCR/user_network'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/html/ocr/ocr_script.py", line 8, in <module>
    reader = easyocr.Reader(['en'], model_storage_directory='/var/www/html/ocr/model')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/.venv/lib/python3.11/site-packages/easyocr/easyocr.py", line 65, in __init__
    Path(self.user_network_directory).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.11/pathlib.py", line 1121, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.11/pathlib.py", line 1117, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/var/www/.EasyOCR'

`

**Comment by MrSlimbrowser** [comment]
This works fine for me
```
reader = easyocr.Reader(['en'], recog_network='best_accuracy', user_network_directory="./user_network", model_storage_directory="./model")
```
