### ISSUE TITLE
installation issues on several platforms

### ISSUE THREAD

**Issue by gs7495945jglolfkgtjoiu** [JaidedAI/EasyOCR#144]
I was unable to install the package with "pip install easyocr" on following platforms:
- Notebook with Linux Mint 19:
`cannot paste what's missing, because I tried installing missing dependencies and now have more errors than before`
- Raspberry PI 0W:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/_internal/operations/prepare.py", line 283, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/lib/python2.7/dist-packages/pip/_internal/download.py", line 836, in unpack_url
    progress_bar=progress_bar
  File "/usr/lib/python2.7/dist-packages/pip/_internal/download.py", line 673, in unpack_http_url
    progress_bar)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/download.py", line 897, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/download.py", line 617, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/utils/hashes.py", line 48, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/_internal/download.py", line 585, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/_internal/utils/ui.py", line 159, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/_internal/download.py", line 574, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.24.1-py2.py3-none-any.whl/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.24.1-py2.py3-none-any.whl/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 63, in read                                                                        self._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError
```
It would be beneficial to clearly specify needed dependencies and add this to installation instructions,

g

**Comment by rkcosmos** [comment]
no idea, list of dependencies is [here](https://github.com/JaidedAI/EasyOCR/blob/master/requirements.txt). Normally pip would take care of that automatically.

**Comment by TemporalAgent7** [comment]
A docker would be great and easier to get started with. Getting the "right" pytorch thing installed on Windows was pretty frustrating as well.

**Comment by rkcosmos** [comment]
Agree with adding docker file

**Comment by saurabhit1127** [comment]
I have also faced problems while doing pip install easyocr.
corrected using the following steps:
1>creating a new anaconda environment: conda create -n easyocr python==3.6.5 
2>activate easyocr
3>conda install pytorch torchvision cpuonly -c pytorch
2>pip install easyocr

**Comment by rkcosmos** [comment]
add Dockerfile by #172, thanks to @ghandic

**Comment by gs7495945jglolfkgtjoiu** [comment]
Can someone pls give basic instructions how to use this docker package?
I managed to pull from docker.io with `docker pull challisa/easyocr`.
However when I try `docker run challisa/easyocr` I get:
`standard_init_linux.go:211: exec user process caused "exec format error"`
Now what (I'm running it on 32bit XUbuntu distro)...

**Comment by ghandic** [comment]
Will need to be added into the README but your problem seems to be something on your system (maybe being 32bit installation?)

You could try to build the container yourself

```bash
git clone https://github.com/JaidedAI/EasyOCR.git
cd EasyOCR
docker build . -t challisa/easyocr
docker run -it challisa/easyocr
```

**Comment by gs7495945jglolfkgtjoiu** [comment]
After I googled it, it seems, that might be an architecture issue. I'm trying to run the docker build for 64bit systems on i686 system.
Is there any chance, that someone makes i686 version of docker?

**Comment by ghandic** [comment]
You'd have to have a check online, 6 years ago they didn't support it but maybe it's on their roadmap. I thought raspberry pi's were ARM chips? I have seen that Docker can run on a raspberry pi but it's a little fiddly. 

This thread might be going beyond the scope of the EasyOCR project now 😁

**Comment by gs7495945jglolfkgtjoiu** [comment]
> 
> 
> Will need to be added into the README but your problem seems to be something on your system (maybe being 32bit installation?)
> 
> You could try to build the container yourself
> 
> ```shell
> git clone https://github.com/JaidedAI/EasyOCR.git
> cd EasyOCR
> docker build . -t challisa/easyocr
> docker run -it challisa/easyocr
> ```

I tried, however received error during build:
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c apt-get update -y &&     apt-get install -y     libglib2.0-0     libsm6     libxext6     libxrender-dev     git     && apt-get autoremove -y     && apt-get clean -y     && rm -rf /var/lib/apt/li' returned a non-zero code: 1

My system is:
Linux eee1005ha-1005HA 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:15:38 UTC 2018 i686 i686 i686 GNU/Linux

**Comment by zhengoogle** [comment]
pip install easyocr MemoryError
Try this cmd:
pip --no-cache-dir install easyocr
