### ISSUE TITLE
Model files won't download

### ISSUE THREAD

**Issue by exiva** [JaidedAI/EasyOCR#194]
Looks like there's an issue with the server for the model files. Returns a 403 forbidden when attempting to download.

```
    reader = easyocr.Reader(['en'], gpu = False)
  File "/Users/travis/.local/share/virtualenvs/ocr-RN8nrvRp/lib/python3.8/site-packages/easyocr/easyocr.py", line 185, in __init__
    urlretrieve(model_url['detector'][0] , DETECTOR_PATH)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by akshaytheau** [comment]
Even I faced the same issue while loading the model for english language 

reader = easyocr.Reader(['en'])

Error :

Downloading detection model, please wait
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-5-6e80277d4ea1> in <module>()
----> 1 reader = easyocr.Reader(['en'])

7 frames
/usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden

**Comment by rkcosmos** [comment]
trying to fix. in the mean time, you can download manually from links on README

**Comment by Wajih88** [comment]
What is the link to the English language ?

**Comment by scaleflake** [comment]
> What is the link to the English language ?

I think you should download "text detection model" (the first one in the list) and "latin model" (the second one)
(not sure about "text detection model", but i downloaded just in case)

**Comment by RitanMihai** [comment]
> trying to fix. in the mean time, you can download manually from links on README

How the code should be? 
I downloaded the files (models) in _C:\Python38\Lib\site-packages\easyocr\model_

I run the code below, like that from README.md, but is not working. How should I write to work? ...
```
import easyocr
reader = easyocr.Reader(['en'])
result = reader.readtext('picture.jpg')
```

**Comment by RitanMihai** [comment]
I found a solution, is hard coded tho... 
In main project in file easyocr.py ([here on git](https://github.com/JaidedAI/EasyOCR/blob/master/easyocr/easyocr.py)) at line 22 (on my version which is 1.1.5)

` 
BASE_PATH = os.path.dirname(__file__)
MODULE_PATH = os.environ.get("MODULE_PATH",
                             os.path.expanduser("~/.EasyOCR/"))
Path(MODULE_PATH+'/model').mkdir(parents=True, exist_ok=True)
`

MODULE_PATH was _C_:\\Users\\PC\\easyocr\\model\\_ and the real one is _C:\Python38\Lib\site-packages\easyocr\model_, where '_PC_' is the name of my computer. So I hard coded that string and now is working.

**Comment by akshaytheau** [comment]
`BASE_PATH = os.path.dirname(__file__)
MODULE_PATH = '/home/akshay/anaconda3/envs/OpenCV/lib/python3.8/site-packages/easyocr'

# detector parameters
DETECTOR_PATH = os.path.join(MODULE_PATH, 'model', 'craft_mlt_25k.pth')`

I did this changes in easyocr.py file still enable to run the code

**Comment by rkcosmos** [comment]
downloaded issue should be fixed in the lastest update. To use last version, you need to uninstall first
`pip uninstall easyocr`

and install directly from source code
`pip install git+git://github.com/jaidedai/easyocr.git`

**Comment by Wyzzard123** [comment]
Thanks @rkcosmos! 

One small thing: After redownloading the package as per your comment, I managed to download the models automatically, but I had to first install the requests library. Maybe the requests library should be automatically installed together with easyocr?

Traceback from my program:

Traceback (most recent call last):
  File ".\translate_manhua.py", line 29, in <module>
    import easyocr
  File "D:\PythonEnvs\AutoManhuaTranslator\lib\site-packages\easyocr\__init__.py", line 1, in <module>
    from .easyocr import Reader
  File "D:\PythonEnvs\AutoManhuaTranslator\lib\site-packages\easyocr\easyocr.py", line 5, in <module>
    from .recognition import get_recognizer, get_text
  File "D:\PythonEnvs\AutoManhuaTranslator\lib\site-packages\easyocr\recognition.py", line 11, in <module>
    from .utils import CTCLabelConverter
  File "D:\PythonEnvs\AutoManhuaTranslator\lib\site-packages\easyocr\utils.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by andmzz** [comment]
Hi @rkcosmos. When i try to install from pip install git+git://github.com/jaidedai/easyocr.git I get this:
 
Running command git clone -q git://github.com/jaidedai/easyocr.git 'C:\Users\andre\AppData\Local\Temp\pip-req-build-_w6avn12'
  ERROR: Error [WinError 2] Impossibile trovare il file specificato while executing command git clone -q git://github.com/jaidedai/easyocr.git 'C:\Users\andre\AppData\Local\Temp\pip-req-build-_w6avn12'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

Do you know how to solve?

**Comment by thanveerkamal** [comment]
Please try to help me if possible....

![Screen_1](https://user-images.githubusercontent.com/68006485/106745183-c0018100-6646-11eb-8e95-f78caa387e89.png)
![Screen_2](https://user-images.githubusercontent.com/68006485/106745192-c263db00-6646-11eb-8f01-e0d3e82dd32b.png)

I get an error of both 
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions.
URLError: <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>

**Comment by omkargupta** [comment]
i m facing below issue

File "E:\Python\Pratics\venv\lib\site-packages\easyocr\easyocr.py", line 90, in __init__
    download_and_unzip(detection_models[detector_model]['url'], detection_models[detector_model]['filename'], self.model_storage_directory, verbose)
  File "E:\Python\Pratics\venv\lib\site-packages\easyocr\utils.py", line 586, in download_and_unzip
    urlretrieve(url, zip_path, reporthook=reporthook)
  File "C:\Users\Onkar\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 283, in urlretrieve
    reporthook(blocknum, bs, size)
  File "E:\Python\Pratics\venv\lib\site-packages\easyocr\utils.py", line 686, in progress_hook
    print(f'\r{prefix} |{bar}| {percent}% {suffix}', end = printEnd)
  File "C:\Users\Onkar\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]

**Comment by PanEsco** [comment]
Böyle bir sorunla karşılaştım çözümü nedir acaba?


Traceback (most recent call last):
  File "c:\Users\Zafer Kaan Çeki\Desktop\plakatanima.py\imageProcessing.py", line 6, in <module>
    import easyocr
ModuleNotFoundError: No module named 'easyocr'
