### ISSUE TITLE
how to convert the specified model to standard onnx model

### ISSUE THREAD

**Issue by vijayky88** [JaidedAI/EasyOCR#288]
Hi,

i have tried converting the provided model in onnx format but getting failed,

print("exported started for recognize model to onnx ")
input_channel = 1
output_channel = 512
hidden_size = 512
num_class   = 6710

model = Model(input_channel, output_channel, hidden_size, num_class)
state_dict = torch.load("/home/vijay/EasyOcr/model/chinese_sim.pth", map_location="cpu")
new_state_dict = OrderedDict()
for key, value in state_dict.items():
    new_key = key[7:]
    new_state_dict[new_key] = value
model.load_state_dict(new_state_dict)

##### below both lines failed 
torch.onnx.export(model, torch.randn(1, 3, 128, 128, device='cpu'), "recog_text.onnx",input_names=("image","text"), output_names=("preds"), opset_version=11)
print(summary(model, (torch.zeros((1, 3, 128, 128)),torch.zeros((1, 512,6710))), show_input=True))

exception:
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    torch.onnx.export(model, torch.randn(1, 3, 128, 128, device='cpu'), "recog_text.onnx",input_names=("image","text"), output_names=("preds"), opset_version=11)
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 366, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 319, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 338, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 426, in forward
    self._force_outplace,
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 412, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 720, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/vijay/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 704, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'text'

#####while i tried for detection model which works fine as below:
print("exported started for detction model to onnx. ")
dectect = get_detector("/home/vijay/EasyOcr/model/craft_mlt_25k.pth", "cpu")
print(summary(dectect, torch.zeros((1, 3, 128, 128)), show_input=True))
torch.onnx.export(dectect, torch.randn(1, 3, 128, 128, device='cpu'), "detect_text.onnx",input_names=("image",), output_names=("preds", "confs"), opset_version=11)
print("detection model exported successfully")

Please provide solution, how can i export the model to onnx successfully

**Comment by jsilvcast** [comment]
I have solved this problem by changing the Forward of the Model. What I have done is to remove the "text" parameter as it is not supposed to be used and is being considered only for the creation of the network.

```
/* Before def forward(self, input, text): */   

def forward(self, input):
        """ Feature extraction stage """
        visual_feature = self.FeatureExtraction(input)
        visual_feature = self.AdaptiveAvgPool(visual_feature.permute(0, 3, 1, 2))
        visual_feature = visual_feature.squeeze(3)

        """ Sequence modeling stage """
        contextual_feature = self.SequenceModeling(visual_feature)

        """ Prediction stage """
        prediction = self.Prediction(contextual_feature.contiguous())

        return prediction
```

Probably if you fix this problem, another problem related to quantization will arise. To solve it, it is necessary to remove these lines of code:
```
if quantize:
            try:
                torch.quantization.quantize_dynamic(model, dtype=torch.qint8, inplace=True)
            except:
                pass
```
