### ISSUE TITLE
NameError: name 'LOGGER' is not defined

### ISSUE THREAD

**Issue by johncaling40** [JaidedAI/EasyOCR#329]
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    results = reader.readtext(image)  # performing the OCR
  File "D:\Miniconda\envs\easyocr\lib\site-packages\easyocr\easyocr.py", line 347, in readtext
    img, img_cv_grey = reformat_input(image)
  File "D:\Miniconda\envs\easyocr\lib\site-packages\easyocr\utils.py", line 672, in reformat_input
    LOGGER.warning('Invalid input type. Suppoting format = string(file path or url), bytes, numpy array')
NameError: name 'LOGGER' is not defined

Latest version of easyocr I have installed. I have also installed pytorch torchvision latest versions.

**Comment by johncaling40** [comment]
I was able to solve issue by running `pip install logger`.

**Comment by dbanavat** [comment]
Check if he image file name or path is correct, or if the image is corrupted.
