### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by HuKaiLang** [JaidedAI/EasyOCR#33]
**OS version:**
Windows 10

**Environment:**
Python version:3.6.8
Pytorch version:stable(1.5.1) cpu only

**Description:**
To Reproduce:
```
import easyocr
reader = easyocr.Reader(['ja'])
print(reader.readtext('test.jpg'))
```
Log:
```
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Downloading detection model, please wait
Download complete
Downloading recognition model, please wait
Download complete
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\projects\python\OCRTest\octTest.py", line 3, in <module>
    reader.readtext('test.jpg')
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "D:\Anaconda3\envs\MachineLearning\lib\site-packages\easyocr\easyocr.py", line 191, in readtext
    exitcode = _main(fd)
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\spawn.py", line 114, in _main
    workers, self.device)
    prepare(preparation_data)
  File "D:\Anaconda3\envs\MachineLearning\lib\site-packages\easyocr\recognition.py", 
line 186, in get_text
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\spawn.py", line 225, in prepare
    ignore_idx, char_group_idx, decoder, beamWidth, device = device)
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda3\envs\MachineLearning\lib\site-packages\easyocr\recognition.py", 
line 104, in recognizer_predict
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    for image_tensors in test_loader:
  File "D:\Anaconda3\envs\MachineLearning\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    run_name="__mp_main__")
  File "D:\Anaconda3\envs\MachineLearning\lib\runpy.py", line 263, in run_path       
    return _MultiProcessingDataLoaderIter(self)
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda3\envs\MachineLearning\lib\runpy.py", line 96, in _run_module_code
  File "D:\Anaconda3\envs\MachineLearning\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda3\envs\MachineLearning\lib\runpy.py", line 85, in _run_code       
    w.start()
    exec(code, run_globals)
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\process.py", line 105, 
in start
  File "d:\projects\python\OCRTest\octTest.py", line 3, in <module>
    reader.readtext('test.jpg')
  File "D:\Anaconda3\envs\MachineLearning\lib\site-packages\easyocr\easyocr.py", line 191, in readtext
    workers, self.device)
  File "D:\Anaconda3\envs\MachineLearning\lib\site-packages\easyocr\recognition.py", 
line 186, in get_text
    ignore_idx, char_group_idx, decoder, beamWidth, device = device)
  File "D:\Anaconda3\envs\MachineLearning\lib\site-packages\easyocr\recognition.py", 
line 104, in recognizer_predict
    for image_tensors in test_loader:
  File "D:\Anaconda3\envs\MachineLearning\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\envs\MachineLearning\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\process.py", line 105, 
in start
    self._popen = self._Popen(self)
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\context.py", line 223, 
in _Popen
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\context.py", line 223, 
in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\context.py", line 322, 
in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\context.py", line 322, 
in _Popen
    return Popen(process_obj)
    return Popen(process_obj)
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\popen_spawn_win32.py", 
line 33, in __init__
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\popen_spawn_win32.py", 
line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\reduction.py", line 60, in dump
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\Anaconda3\envs\MachineLearning\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
```
After I referenced [this](https://stackoverflow.com/questions/50480689/pytorch-torchvision-brokenpipeerror-errno-32-broken-pipe) article, I made the following changes to the `easyocr\recognition.py` and then the program wouldn't crash again.
At line 180:
```
test_loader = torch.utils.data.DataLoader(
        test_data, batch_size=batch_size, shuffle=False,
        num_workers=0, collate_fn=AlignCollate_normal, pin_memory=True)  # before: num_workers=int(workers)
```

**Comment by rkcosmos** [comment]
Looks similar to #3. Another work around for Windows is to wrap everything like this

```
def main():
    read=easyocr.Reader(['en'], gpu=False)
    text =read.readtext('covid.jpg', workers=1, batch_size=1)
    print(text)
    
if __name__ == '__main__':
    main()
```

I think this approach might be better because you can still use multiple workers.

**Comment by HuKaiLang** [comment]
> Looks similar to #3. Another work around for Windows is to wrap everything like this
> 
> ```
> def main():
>     read=easyocr.Reader(['en'], gpu=False)
>     text =read.readtext('covid.jpg', workers=1, batch_size=1)
>     print(text)
>     
> if __name__ == '__main__':
>     main()
> ```
> 
> I think this approach might be better because you can still use multiple workers.

@rkcosmos It works,thanks!
