### ISSUE TITLE
Circular Dependencies on Fresh Install

### ISSUE THREAD

**Issue by nsmithfs** [JaidedAI/EasyOCR#330]
Ubuntu 18.04 (in docker), Ubuntu 20.04

> virtualenv .
> source bin/activate
> pip3 install easyocr
> 

```
import easyocr as eo

reader = eo.Reader(['en'])
result = reader.readtext("srcdata/" + sys.argv[1])

```

Throws error:

```
Traceback (most recent call last):
  File "easyocr.py", line 1, in <module>
    import easyocr as eo
  File "/home/megiddo/Development/frogslayer/tec/ocr/easyocr.py", line 3, in <module>
    reader = eo.Reader(['en'])
AttributeError: partially initialized module 'easyocr' has no attribute 'Reader' (most likely due to a circular import)
```

**Comment by nsmithfs** [comment]
Resolved.

**Comment by MonksterFX** [comment]
How did you resolve it?

**Comment by Anekkkk** [comment]
i fixed it my changing the name of my python script from `easyocr.py`

**Comment by maralzar** [comment]
I have the same error rename your file :))
