### ISSUE TITLE
Window 10 Pillow Install error: The headers or library files could not be found for zlib

### ISSUE THREAD

**Issue by liebig** [JaidedAI/EasyOCR#331]
I am trying to install the library on a Windows 10 PC with pip 20.3.3 and I get the following error:
`The headers or library files could not be found for zlib,
a required dependency when compiling Pillow from source.`

[Maybe the used Pillow version is too old and an update to Pillow 8 would fix this?](https://github.com/python-pillow/Pillow/issues/4242)

Full Log:
```Installing collected packages: Pillow, easyocr
  Attempting uninstall: Pillow
    Found existing installation: pillow 8.0.1
    Uninstalling pillow-8.0.1:
      Successfully uninstalled pillow-8.0.1
    Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\marc\pycharmprojects\test\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Marc\\AppData\\Local\\Temp\\pip-install
-n0sv2674\\pillow_ea060bd110994f7cb64699bfd27baf90\\setup.py'"'"'; __file__='"'"'C:\\Users\\Marc\\AppData\\Local\\Temp\\pip-install-n0sv2674\\pillow_ea060bd110994f7cb64699bfd27baf90\\setu
p.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record
 'C:\Users\Marc\AppData\Local\Temp\pip-record-7jimv80y\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\marc\pycharmprojects\test\venv\inclu
de\site\python3.9\Pillow'
         cwd: C:\Users\Marc\AppData\Local\Temp\pip-install-n0sv2674\pillow_ea060bd110994f7cb64699bfd27baf90\
    Complete output (176 lines):
    C:\Users\Marc\AppData\Local\Temp\pip-install-n0sv2674\pillow_ea060bd110994f7cb64699bfd27baf90\setup.py:28: RuntimeWarning: Pillow does not yet support Python 3.9 and does not yet prov
ide prebuilt Windows binaries. We do not recommend building from source on Windows.
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\PIL
    copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\features.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Image.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TarIO.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_binary.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_util.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_version.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\__init__.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\__main__.py -> build\lib.win-amd64-3.9\PIL
    running egg_info
    writing src\Pillow.egg-info\PKG-INFO
    writing dependency_links to src\Pillow.egg-info\dependency_links.txt
    writing top-level names to src\Pillow.egg-info\top_level.txt
    reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "C:\Users\Marc\AppData\Local\Temp\pip-install-n0sv2674\pillow_ea060bd110994f7cb64699bfd27baf90\setup.py", line 852, in <module>
        setup(
      File "c:\users\marc\pycharmprojects\test\venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\marc\pycharmprojects\test\venv\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\Marc\AppData\Local\Temp\pip-install-n0sv2674\pillow_ea060bd110994f7cb64699bfd27baf90\setup.py", line 687, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Marc\AppData\Local\Temp\pip-install-n0sv2674\pillow_ea060bd110994f7cb64699bfd27baf90\setup.py", line 903, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html


    ----------------------------------------
  Rolling back uninstall of pillow
  Moving to c:\users\marc\pycharmprojects\test\venv\lib\site-packages\pil\
   from C:\Users\Marc\PycharmProjects\test\venv\Lib\site-packages\~il
  Moving to c:\users\marc\pycharmprojects\test\venv\lib\site-packages\pillow-8.0.1.dist-info\
   from C:\Users\Marc\PycharmProjects\test\venv\Lib\site-packages\~illow-8.0.1.dist-info
ERROR: Command errored out with exit status 1: 'c:\users\marc\pycharmprojects\test\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Marc\\
AppData\\Local\\Temp\\pip-install-n0sv2674\\pillow_ea060bd110994f7cb64699bfd27baf90\\setup.py'"'"'; __file__='"'"'C:\\Users\\Marc\\AppData\\Local\\Temp\\pip-install-n0sv2674\\pillow_ea060
bd110994f7cb64699bfd27baf90\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '
"'"'exec'"'"'))' install --record 'C:\Users\Marc\AppData\Local\Temp\pip-record-7jimv80y\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\marc\
pycharmprojects\test\venv\include\site\python3.9\Pillow' Check the logs for full command output.
```

**Comment by adinfinitedevices** [comment]
Hi, I had a similiar error.
Solved it installing Python 3.7 (instead of actually installed Python 3.8).

**Comment by liebig** [comment]
Thank you. I had to use a other numpy version but now I can install it.

```pip uninstall numpy
pip install numpy==1.19.3```

**Comment by JhosefMatheus** [comment]
@liebig i have the same problem and i don't know how to solve it, can you help me please?

**Comment by liebig** [comment]
@JhosefMatheus Try to use Python 3.7 or numpy in version 1.19.3.
