### ISSUE TITLE
CUDA out of memory error while trying to transcribe a lot of images.

### ISSUE THREAD

**Issue by cubeserverdev** [JaidedAI/EasyOCR#430]
Like the title suggests I am trying to transcribe thousands of images but am running into an out of memory error:

```
Traceback (most recent call last):
  File "C:/Users/cubeservdev/Dev/OCRTest/ocr_test.py", line 15, in <module>
    transcription = reader.readtext(f'images/{image_file}', detail=0)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\easyocr\easyocr.py", line 378, in readtext
    add_margin, False)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\easyocr\easyocr.py", line 273, in detect
    False, self.device, optimal_num_chars)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\easyocr\detection.py", line 81, in get_textbox
    bboxes, polys = test_net(canvas_size, mag_ratio, detector, image, text_threshold, link_threshold, low_text, poly, device, estimate_num_chars)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\easyocr\detection.py", line 38, in test_net
    y, feature = net(x)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\torch\nn\parallel\data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\easyocr\craft.py", line 60, in forward
    sources = self.basenet(x)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\easyocr\model\modules.py", line 61, in forward
    h = self.slice1(X)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\torch\nn\modules\batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "C:\ProgramData\Anaconda3\envs\EasyOCRTest\lib\site-packages\torch\nn\functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 1.41 GiB (GPU 0; 3.00 GiB total capacity; 1.75 GiB already allocated; 0 bytes free; 1.84 GiB reserved in total by PyTorch)
libpng warning: iCCP: known incorrect sRGB profile
```

```py
import os
import time
import easyocr


if __name__ == '__main__':
    images = os.listdir('images')
    image_count = len(images)
    reader = easyocr.Reader(['ch_sim', 'en'], recog_network='latin_g1', gpu=True)
    for index, image_file in enumerate(images):
        text_file_name = image_file.split('.')[0]
        print(f'Transcribing ({index}/{image_count}) {text_file_name}', end='')
        start_time = time.time()
        with open(f'transcriptions/{text_file_name}.txt', 'w+', encoding='utf-8') as text_file:
            transcription = reader.readtext(f'images/{image_file}', detail=0)
            text_file.write('\n'.join(transcription))
        print(f' finished in {round(time.time() - start_time, 2)} seconds.')
```

I don't think the memory issues/leaks are being caused by my code but I could most definitely be wrong. How can I resolve this issue?

**Comment by rkcosmos** [comment]
`recog_network='latin_g1'` is for latin characters. I think you should use `recog_network='zh_sim_g2'`. It is also smaller model and may help with your memory issue.

**Comment by cubeserverdev** [comment]
Switching to the smaller model did not seem to help with the OOM error.

**Comment by rkcosmos** [comment]
How big (pixel * pixel) are your images? Is it possible that the program die when you are passing bigger image in?

**Comment by SamSamhuns** [comment]
By default, the detection model uses `torch.nn.DataParallel` in `easyocr/detection.py`. So even if you have multiple GPUs with even memory, if one of them is occupied, you'll get a CUDA OOM error. 

Maybe try using one GPU device which you know has enough memory by changing the ` net = torch.nn.DataParallel(net).to(device)` to  `device="cuda:0"; net = net.to(device)`

```
def get_detector(trained_model, device='cpu', quantize=True, cudnn_benchmark=False):
    net = CRAFT()

    if device == 'cpu':
        net.load_state_dict(copyStateDict(torch.load(trained_model, map_location=device)))
        if quantize:
            try:
                torch.quantization.quantize_dynamic(net, dtype=torch.qint8, inplace=True)
            except:
                pass
    else:
        net.load_state_dict(copyStateDict(torch.load(trained_model, map_location=device)))
        net = torch.nn.DataParallel(net).to(device)
        cudnn.benchmark = cudnn_benchmark

    net.eval()
    return net
```
