### ISSUE TITLE
Unable to start to use

### ISSUE THREAD

**Issue by falconlmf** [JaidedAI/EasyOCR#484]
Hi! I just installed and wanted to start with the readme example, however failed when it tries to download the detection model.

Python3.7.0

`(easyocr) ➜  cgc python3                                  
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import easyocr
reader = easyocr.Reader(['ch_tra', 'en'])
>>> reader = easyocr.Reader(['ch_tra', 'en'])
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Downloading detection model, please wait. This may take several minutes depending upon your network connection.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/falcon/Work/cgc/easyocr/lib/python3.7/site-packages/easyocr/easyocr.py", line 89, in __init__
    download_and_unzip(detection_models[detector_model]['url'], detection_models[detector_model]['filename'], self.model_storage_directory, verbose)
  File "/Users/falcon/Work/cgc/easyocr/lib/python3.7/site-packages/easyocr/utils.py", line 562, in download_and_unzip
    urlretrieve(url, zip_path, reporthook=reporthook)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
>>> `

**Comment by AO-Mondmann** [comment]
exactly the same for me, like it's always like that. I want to use something but it's not working anymore

**Comment by falconlmf** [comment]
> exactly the same for me, like it's always like that. I want to use something but it's not working anymore

I eventually switched to use mss for (partially) screenshooting and cv2's templatematching feature, can go up to 60fps for me :)

**Comment by AO-Mondmann** [comment]
Thank you for letting me know. I guess template matching won't help as I need to get text out of a handwritten + copied invoice PDF file and Template matching can't do this right? As the data isn't always the same

I don't get why no one of the devs replies, maybe it's working for everyone else :D

**Comment by falconlmf** [comment]
> Thank you for letting me know. I guess template matching won't help as I need to get text out of a handwritten + copied invoice PDF file and Template matching can't do this right? As the data isn't always the same
> 
> I don't get why no one of the devs replies, maybe it's working for everyone else :D

You're right, OCR should be the correct way. However I also used this method for digit (by digit) as well. :( 
I am checking the map coordination:
![Screenshot 2021-07-13 at 13 16 00](https://user-images.githubusercontent.com/13671349/126330613-1d1602fe-125e-4a32-9fcd-a3e4b7605b12.png)

**Comment by ankrgyl** [comment]
This error usually points to an issue with your OS X Python configuration. You need to run a command [like this](https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore) for your Python installation.
