### ISSUE TITLE
easyocr.Reader raises error

### ISSUE THREAD

**Issue by research-boy** [JaidedAI/EasyOCR#498]
>>> import easyocr
>>> reader = easyocr.Reader(['ch_sim','en'] , gpu= True)
Downloading detection model, please wait. This may take several minutes depending upon your network connection.
Traceback (most recent call last):---------------------------| 2.0% Complete
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/easyocr-1.4-py3.6.egg/easyocr/easyocr.py", line 90, in __init__
    download_and_unzip(detection_models[detector_model]['url'], detection_models[detector_model]['filename'], self.model_storage_directory, verbose)
  File "/usr/local/lib/python3.6/dist-packages/easyocr-1.4-py3.6.egg/easyocr/utils.py", line 585, in download_and_unzip
    urlretrieve(url, zip_path, reporthook=reporthook)
  File "/usr/lib/python3.6/urllib/request.py", line 284, in urlretrieve
    reporthook(blocknum, bs, size)
  File "/usr/local/lib/python3.6/dist-packages/easyocr-1.4-py3.6.egg/easyocr/utils.py", line 685, in progress_hook
    print(f'\r{prefix} |{bar}| {percent}% {suffix}', end = printEnd)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2588' in position 12: ordinal not in range(128)

**Comment by research-boy** [comment]
solved this with export PYTHONIOENCODING=utf-8
