### ISSUE TITLE
The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable.

### ISSUE THREAD

**Issue by snoop2head** [JaidedAI/EasyOCR#53]
Since I failed to execute quickstart with poetry package on #52 , I switched package manager to pip. But it fails with other message.

## Development Environment
* Mac OS Catalina 10.15.5
* pyenv virtual environment
* Python 3.8.3 
* pip as package manager

### Set up Virtual Environment and Dependencies
```shell
# zsh shell
pyenv virtualenv 3.8.3 OCR
pyenv activate OCR
```
### Install easyocr via pip
```
pip install easyocr
```

### Run Python File

```python
# detect.py
import easyocr

reader = easyocr.Reader(["en", "ko"], gpu=False)
reader.readtext("./images/fc850139e7d6f37f4af7624e3cdbbcef.jpg")
```

[Image Source is this jpg picture](https://i.pinimg.com/736x/fc/85/01/fc850139e7d6f37f4af7624e3cdbbcef.jpg)

```shell
# zsh shell
python detect.py
```
```shell
# zsh shell error message
Using CPU. Note: This module is much faster with a GPU.
Using CPU. Note: This module is much faster with a GPU.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/noopy/OCR_KR/detect.py", line 4, in <module>
    reader.readtext("./images/fc850139e7d6f37f4af7624e3cdbbcef.jpg")
  File "/Users/noopy/.pyenv/versions/ocr/lib/python3.8/site-packages/easyocr/easyocr.py", line 189, in readtext
    result = get_text(self.character, imgH, max_width, self.recognizer, self.converter, image_list,\
  File "/Users/noopy/.pyenv/versions/ocr/lib/python3.8/site-packages/easyocr/recognition.py", line 185, in get_text
    result1 = recognizer_predict(recognizer, converter, test_loader,batch_max_length,\
  File "/Users/noopy/.pyenv/versions/ocr/lib/python3.8/site-packages/easyocr/recognition.py", line 104, in recognizer_predict
    for image_tensors in test_loader:
  File "/Users/noopy/.pyenv/versions/ocr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/noopy/.pyenv/versions/ocr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
    w.start()
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by rkcosmos** [comment]
Please upgrade to version 1.1.2 via pip. The issue should be fixed

**Comment by snoop2head** [comment]
Upgraded and it works! Thanks 🙏
Why do you think pip has not downloaded the most recent version in the first place?

**Comment by rkcosmos** [comment]
Project is in rapid development. I usually wait for a few days before upload new version to pip.

**Comment by snoop2head** [comment]
Ah, I see. Thanks for the help!
