### ISSUE TITLE
raise ScannerError

### ISSUE THREAD

**Issue by fengjinhanzhenshuai** [JaidedAI/EasyOCR#532]
>>> reader = easyocr.Reader(['ch_sim','en'],recog_network='custom')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda3\Lib\site-packages\EasyOCR-master\easyocr\easyocr.py", line 204, in __init__
    recog_config = yaml.load(file, Loader=yaml.FullLoader)
  File "D:\anaconda3\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "D:\anaconda3\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "D:\anaconda3\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "D:\anaconda3\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "D:\anaconda3\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "D:\anaconda3\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "D:\anaconda3\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "D:\anaconda3\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "D:\anaconda3\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "D:\anaconda3\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "D:\anaconda3\lib\site-packages\yaml\scanner.py", line 235, in fetch_more_tokens
    return self.fetch_tag()
  File "D:\anaconda3\lib\site-packages\yaml\scanner.py", line 632, in fetch_tag
    self.tokens.append(self.scan_tag())
  File "D:\anaconda3\lib\site-packages\yaml\scanner.py", line 967, in scan_tag
    suffix = self.scan_tag_uri('tag', start_mark)
  File "D:\anaconda3\lib\site-packages\yaml\scanner.py", line 1393, in scan_tag_uri
    raise ScannerError("while parsing a %s" % name, start_mark,
yaml.scanner.ScannerError: while parsing a tag
  in "C:\Users\Administrator\.EasyOCR/user_network\custom.yaml", line 30, column 17
expected URI, but found '\\'
  in "C:\Users\Administrator\.EasyOCR/user_network\custom.yaml", line 30, column 18

I try to change "C:\Users\Administrator\.EasyOCR/user_network\custom.yaml" to "C:\Users\Administrator\.EasyOCR\user_network\custom.yaml",but it did not work
How can I fix it?Thanks!

**Comment by rkcosmos** [comment]
I think the problem might be in your `custom.yaml` file
