### ISSUE TITLE
ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad'

### ISSUE THREAD

**Issue by Code4SAFrankie** [JaidedAI/EasyOCR#59]
```
E:\WPy-3710\python-3.7.1.amd64>.\python.exe
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import easyocr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\easyocr\__init__.py", line 1, in <module>
    from .easyocr import Reader
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\easyocr\easyocr.py", line 1, in <module>
    from .detection import get_detector, get_textbox
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\easyocr\detection.py", line 10, in <module>
    from .imgproc import resize_aspect_ratio, normalizeMeanVariance
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\easyocr\imgproc.py", line 8, in <module>
    from skimage import io
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\skimage\__init__.py", line 167, in <module>
    from .util.dtype import (img_as_float32,
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\skimage\util\__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\numpy\lib\arraypad.py)
```

Can't `import easyocr` on WinPython 3.71 on Windows 10. Installed without errors though

**Comment by rkcosmos** [comment]
Probably update numpy and scikit-learn see [this stackoverflow](https://stackoverflow.com/questions/54241226/importerror-cannot-import-name-validate-lengths)

**Comment by Code4SAFrankie** [comment]
`pip install --upgrade scikit-image` has indeed fixed it.
