### ISSUE TITLE
Executing cli.py error

### ISSUE THREAD

**Issue by rakshanaa** [JaidedAI/EasyOCR#652]
while executing cli.py i am facing this issue

Traceback (most recent call last):
  File "cli.py", line 278, in <module>
    main()
  File "cli.py", line 238, in main
    reader = easyocr.Reader(lang_list=args.lang,
  File "/home/EasyOCR/easyocr/easyocr.py", line 241, in __init__
    self.recognizer, self.converter = get_recognizer(recog_network, network_params,
  File "/home/EasyOCR/easyocr/recognition.py", line 163, in get_recognizer
    model_pkg = importlib.import_module("easyocr.model.vgg_model")
  File "/home/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 970, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'easyocr.model'; 'easyocr' is not a package

**Comment by rakshanaa** [comment]
i got the solution
