### ISSUE TITLE
installation does not work literally at all

### ISSUE THREAD

**Issue by ilovedogs1235** [JaidedAI/EasyOCR#680]
"subprocess-exited-with-error"
i think it's an error in PIL???
output log:
`Collecting easyocr
  Using cached easyocr-1.4.1-py3-none-any.whl (63.6 MB)
Requirement already satisfied: scipy in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from easyocr) (1.8.0)
Requirement already satisfied: python-bidi in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from easyocr) (0.4.2)
Requirement already satisfied: torch in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from easyocr) (1.11.0)
Collecting torchvision>=0.5
  Using cached torchvision-0.12.0-cp310-cp310-win_amd64.whl (1.0 MB)
Requirement already satisfied: PyYAML in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from easyocr) (6.0)
Collecting Pillow<8.3.0
  Using cached Pillow-8.2.0.tar.gz (47.9 MB)
  Preparing metadata (setup.py) ... done
Collecting opencv-python-headless
  Using cached opencv_python_headless-4.5.5.64-cp36-abi3-win_amd64.whl (35.3 MB)
Requirement already satisfied: numpy in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from easyocr) (1.22.3)
Collecting scikit-image
  Using cached scikit_image-0.19.2-cp310-cp310-win_amd64.whl (12.6 MB)
Requirement already satisfied: typing-extensions in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from torchvision>=0.5->easyocr) (4.0.1)
Requirement already satisfied: requests in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from torchvision>=0.5->easyocr) (2.26.0)
Requirement already satisfied: six in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from python-bidi->easyocr) (1.16.0)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->easyocr) (1.3.0)
Requirement already satisfied: packaging>=20.0 in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->easyocr) (21.3)
Collecting imageio>=2.4.1
  Using cached imageio-2.16.1-py3-none-any.whl (3.3 MB)
Collecting networkx>=2.2
  Using cached networkx-2.7.1-py3-none-any.whl (2.0 MB)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->easyocr) (2022.2.9)
Collecting imageio>=2.4.1
  Using cached imageio-2.16.0-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.15.0-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.14.1-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.14.0-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.13.5-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.13.4-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.13.3-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.13.2-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.13.1-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.13.0-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.12.0-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.11.1-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.11.0-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.10.5-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.10.4-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.10.3-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.10.2-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.10.1-py3-none-any.whl (3.3 MB)
  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from packaging>=20.0->scikit-image->easyocr) (3.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision>=0.5->easyocr) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision>=0.5->easyocr) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision>=0.5->easyocr) (2.0.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision>=0.5->easyocr) (3.3)
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [177 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-3.10\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext
     
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
      Traceback (most recent call last):
        File "C:\Users\blablabla\AppData\Local\Temp\pip-install-0g3a3fmy\pillow_d106b7215da24a568173688ecf468484\setup.py", line 976, in <module>
          setup(
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 340, in run
          self.build_extensions()
        File "C:\Users\blablabla\AppData\Local\Temp\pip-install-0g3a3fmy\pillow_d106b7215da24a568173688ecf468484\setup.py", line 788, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: zlib
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\blablabla\AppData\Local\Temp\pip-install-0g3a3fmy\pillow_d106b7215da24a568173688ecf468484\setup.py", line 1033, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
     
      C:\Users\blablabla\AppData\Local\Temp\pip-install-0g3a3fmy\pillow_d106b7215da24a568173688ecf468484\setup.py:46: RuntimeWarning: Pillow 8.2.0 does not support Python 3.10 and does not provide prebuilt 
Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow, opencv-python-headless, networkx, torchvision, imageio, scikit-image, easyocr
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.0.1
    Uninstalling Pillow-9.0.1:
      Successfully uninstalled Pillow-9.0.1
  Running setup.py install for Pillow ... error
  error: subprocess-exited-with-error

  × Running setup.py install for Pillow did not run successfully.
  │ exit code: 1
  ╰─> [179 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-3.10\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-3.10\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext
     
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
      Traceback (most recent call last):
        File "C:\Users\blablabla\AppData\Local\Temp\pip-install-0g3a3fmy\pillow_d106b7215da24a568173688ecf468484\setup.py", line 976, in <module>
          setup(
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\command\install.py", line 568, in run
          self.run_command('build')
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 340, in run
          self.build_extensions()
        File "C:\Users\blablabla\AppData\Local\Temp\pip-install-0g3a3fmy\pillow_d106b7215da24a568173688ecf468484\setup.py", line 788, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: zlib
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\blablabla\AppData\Local\Temp\pip-install-0g3a3fmy\pillow_d106b7215da24a568173688ecf468484\setup.py", line 1033, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
     
      C:\Users\blablabla\AppData\Local\Temp\pip-install-0g3a3fmy\pillow_d106b7215da24a568173688ecf468484\setup.py:46: RuntimeWarning: Pillow 8.2.0 does not support Python 3.10 and does not provide prebuilt 
Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages
  Rolling back uninstall of pillow
  Moving to c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages\pil\
   from C:\Users\blablabla\AppData\Local\Programs\Python\Python310\Lib\site-packages\~il
  Moving to c:\users\blablabla\appdata\local\programs\python\python310\lib\site-packages\pillow-9.0.1.dist-info\
   from C:\Users\blablabla\AppData\Local\Programs\Python\Python310\Lib\site-packages\~illow-9.0.1.dist-info
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

PLEASE god help me with this

**Comment by anylanes** [comment]
there was a similar problem. when I figured it out, I realized that the maximum version of python that can work with easyocr is 3.9, since this library uses pillow version 8.2.0. I use Pycharm and there, when creating a new project, I also clicked these two boxes, and only after that the library was installed normally
<img width="793" alt="1" src="https://user-images.githubusercontent.com/101903547/159082110-40f93cf4-1c02-494e-a622-f251c0f5512b.png">
.
