### ISSUE TITLE
DataLoader error 

### ISSUE THREAD

**Issue by Mahmuod1** [JaidedAI/EasyOCR#757]
first Appreciated for your Repo :
this error i faced it when i load the data 
i think the error happen in the last loaded batch of dataset from :
[/content/EasyOCR/trainer/train.py](https://localhost:8080/#) in train(opt, show_number, amp)
    203             scaler.update()
    204         else:
--> 205             image_tensors, labels = train_dataset.get_batch()
    206             image = image_tensors.to(device)
    207             text, length = converter.encode(labels, batch_max_length=opt.batch_max_length)
i print the loaded batches and i get batches for 3 minute and once get this error
this is my opt:
"""
{

{'FT': True,
 'FeatureExtraction': 'VGG',
 'PAD': True,
 'Prediction': 'CTC',
 'SequenceModeling': 'BiLSTM',
 'Transformation': 'None',
 'batch_max_length': 100,
 'batch_ratio': ['1'],
 'batch_size': 32,
 'beta1': 0.9,
 'character': "0123456789٠١٢٣٤٥٦٧٨٩!#/$%&'\\()*+,-./:;<=>?@[\\]^_`{|}~«»؟،؛ءabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZءآأؤإئااًابةتثجحخدذرزسشصضطظعغفقكلمنهوىيٱٹپچڈڑژکڭگںھۀہۂۃۆۇۈۋیېےۓ",
 'contrast_adjust': False,
 'data_filtering_off': True,
 'decode': 'greedy',
 'eps': 1e-08,
 'experiment_name': 'en_filtered',
 'freeze_FeatureFxtraction': False,
 'freeze_SequenceModeling': False,
 'grad_clip': 5,
 'hidden_size': 512,
 'imgH': 64,
 'imgW': 600,
 'input_channel': 1,
 'lang_char': 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZءآأؤإئااًابةتثجحخدذرزسشصضطظعغفقكلمنهوىيٱٹپچڈڑژکڭگںھۀہۂۃۆۇۈۋیېےۓ',
 'lr': 1.0,
 'manualSeed': 1111,
 'new_prediction': False,
 'num_class': 185,
 'num_fiducial': 20,
 'num_iter': 300000,
 'number': '0123456789٠١٢٣٤٥٦٧٨٩',
 'optim': False,
 'output_channel': 512,
 'rgb': False,
 'rho': 0.95,
 'saved_model': '/content/drive/MyDrive/saved_models/en_filtered/best_accuracy.pth',
 'select_data': '/',
 'sensitive': True,
 'symbol': "!#/$%&'\\()*+,-./:;<=>?@[\\]^_`{|}~«»؟،؛ء",
 'total_data_usage_ratio': 1.0,
 'train_data': '/content/newCreatedTextImagesFrontId_train_tall',
 'valInterval': 2000,
 'valid_data': '/content/newCreatedTextImagesFrontId_train_tall_eval',
 'workers': 1}

}
"""
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataset.py", line 471, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataset.py", line 416, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/content/EasyOCR/trainer/dataset.py", line 177, in __getitem__
    index = self.filtered_index_list[index]
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py", line 2275, in __getitem__
    return super().__getitem__(key)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py", line 2222, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py", line 3579, in _get_value
    loc = engine.get_loc(index)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2131, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2140, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 40000

**Comment by SardarArslan** [comment]
How did you solve the error?

**Comment by ftmasadi** [comment]
> 
This is my problem. Did you solve this problem?

**Comment by ftmasadi** [comment]
> How did you solve the error?

 Did you solve this problem?

**Comment by Khaled-Mohammed-Abdelgaber** [comment]
me too, how did you solve it
