### ISSUE TITLE
Numpy is not available

### ISSUE THREAD

**Issue by anilnautiyal7** [JaidedAI/EasyOCR#797]
I am trying to use the easyocr repo by installing all the prerequisites but when I try to run it, it gives the following error.

C:\Data\Fanal\RMG AI>easyocr -l ch_sim en -f inv.jpg --detail=1 --gpu=True
C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\detection\anchor_utils.py:63: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  device: torch.device = torch.device("cpu"),
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:252: UserWarning: Accessing the model URLs via the internal dictionary of the module is deprecated since 0.13 and will be removed in 0.15. Please access them via the appropriate Weights Enum instead.
  warnings.warn(
C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Traceback (most recent call last):
  File "C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\nauti\AppData\Local\Programs\Python\Python310\Scripts\easyocr.exe\__main__.py", line 7, in <module>
  File "C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\cli.py", line 246, in main
    for line in reader.readtext(args.file,\
  File "C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\easyocr.py", line 392, in readtext
    horizontal_list, free_list = self.detect(img, min_size, text_threshold,\
  File "C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\easyocr.py", line 279, in detect
    text_box_list = get_textbox(self.detector, img, canvas_size, mag_ratio,
  File "C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\detection.py", line 96, in get_textbox
    bboxes_list, polys_list = test_net(canvas_size, mag_ratio, detector,
  File "C:\Users\nauti\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\detection.py", line 42, in test_net
    x = torch.from_numpy(np.array(x))
RuntimeError: Numpy is not available

I have checked that all the libraries related to numpy, torch, torchvision all are installed properly.

**Comment by Atri10** [comment]
How did you solved it?

**Comment by Yes-buter** [comment]
请问你解决了吗？怎么解决的？
