### ISSUE TITLE
ModuleNotFoundError: No module named 'easyocr/DBNet'

### ISSUE THREAD

**Issue by gizmo84** [JaidedAI/EasyOCR#830]
Hi everyone :)

First I want to thank you for this great library! Great job! :)

I wanted to try the new detector DBNet, but I currently get an error:

```
import easyocr

reader = easyocr.Reader(["en"], detect_network="dbnet18")
```

witch is producing following Exception:

```
Traceback (most recent call last):
  File "C:\Users\b30768\PycharmProjects\ocr-service\sandbox.py", line 10, in <module>
    reader = easyocr.Reader(["en"], detect_network="dbnet18")
  File "C:\Users\b30768\PycharmProjects\ocr-service\venv\lib\site-packages\easyocr\easyocr.py", line 210, in __init__
    self.detector = self.initDetector(detector_path)
  File "C:\Users\b30768\PycharmProjects\ocr-service\venv\lib\site-packages\easyocr\easyocr.py", line 272, in initDetector
    return self.get_detector(detector_path, self.device, self.quantize, cudnn_benchmark=self.cudnn_benchmark)
  File "C:\Users\b30768\PycharmProjects\ocr-service\venv\lib\site-packages\easyocr\detection_db.py", line 128, in get_detector
    dbnet.construct_model(dbnet.configs['resnet18']['model'])
  File "C:\Users\b30768\PycharmProjects\ocr-service\venv\lib\site-packages\easyocr\DBNet\DBNet.py", line 168, in construct_model
    self.model = Configurable.construct_class_from_config(config).structure.builder.build(self.device)
  File "C:\Users\b30768\PycharmProjects\ocr-service\venv\lib\site-packages\easyocr\DBNet\model\constructor.py", line 40, in construct_class_from_config
    cls = Configurable.extract_class_from_args(args)
  File "C:\Users\b30768\PycharmProjects\ocr-service\venv\lib\site-packages\easyocr\DBNet\model\constructor.py", line 47, in extract_class_from_args
    module = importlib.import_module(package)
  File "C:\Users\b30768\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'easyocr/DBNet'
```

I tried several things but I don't get it work, I thing there is a missing __init__.py or an import but I don't get it.

Could someone try to reproduce it ?

**Comment by kenho211** [comment]
also having the same problem

**Comment by rkcosmos** [comment]
thanks for the report @gizmo84, are you on Windows as well @kenho211?

**Comment by kenho211** [comment]
Yes on Windows

**Comment by gizmo84** [comment]
Yep, Windows (for development). Will try my code on Docker later today and come back to you.

**Comment by xor0x** [comment]
Also having the same problem, using Python 3.10 and Windows 11

**Comment by rkcosmos** [comment]
thanks, my team think they have found the cause. Next version will fix this (will be released in a few days).

**Comment by gizmo84** [comment]
@rkcosmos thanks for the new version you released yesterday. Unfortunatly it is currently not available on PyPi: https://pypi.org/project/easyocr/ (still 1.6.0)

**Comment by gizmo84** [comment]
Ok, 1.6.1 is now available on PyPi. ModuleNotFoundError is gone but I get a new error. I will open a new issue.
