### ISSUE TITLE
ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by RAbraham** [JaidedAI/EasyOCR#84]
Hi,
I'm on Ubuntu 20.04, python 3.6.9 using pyenv
I've installed the following:
```
sudo apt install liblzma-dev
```
On `import easyocr`, I get the following error.

```
(trial_env) ➜  bht-utils python
Python 3.6.9 (default, Jun 15 2020, 10:01:55) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import easyocr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rajiv/Documents/dev/bht/bht-utils/trial_env/lib/python3.6/site-packages/easyocr/__init__.py", line 1, in <module>
    from .easyocr import Reader
  File "/home/rajiv/Documents/dev/bht/bht-utils/trial_env/lib/python3.6/site-packages/easyocr/easyocr.py", line 1, in <module>
    from .detection import get_detector, get_textbox
  File "/home/rajiv/Documents/dev/bht/bht-utils/trial_env/lib/python3.6/site-packages/easyocr/detection.py", line 10, in <module>
    from .imgproc import resize_aspect_ratio, normalizeMeanVariance
  File "/home/rajiv/Documents/dev/bht/bht-utils/trial_env/lib/python3.6/site-packages/easyocr/imgproc.py", line 8, in <module>
    from skimage import io
  File "/home/rajiv/Documents/dev/bht/bht-utils/trial_env/lib/python3.6/site-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/home/rajiv/Documents/dev/bht/bht-utils/trial_env/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 23, in <module>
    from .collection import imread_collection_wrapper
  File "/home/rajiv/Documents/dev/bht/bht-utils/trial_env/lib/python3.6/site-packages/skimage/io/collection.py", line 13, in <module>
    from tifffile import TiffFile
  File "/home/rajiv/Documents/dev/bht/bht-utils/trial_env/lib/python3.6/site-packages/tifffile/__init__.py", line 3, in <module>
    from .tifffile import __doc__, __all__, __version__, main
  File "/home/rajiv/Documents/dev/bht/bht-utils/trial_env/lib/python3.6/site-packages/tifffile/tifffile.py", line 11315, in <module>
    import lzma
  File "/home/rajiv/.pyenv/versions/3.6.9/lib/python3.6/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

**Comment by RAbraham** [comment]
It's a `pyenv` issue. It was solved by following [this](https://github.com/pandas-dev/pandas/issues/27532#issuecomment-514044754)
Thanks
