### ISSUE TITLE
Unable to parse image from url-based source

### ISSUE THREAD

**Issue by gslin** [JaidedAI/EasyOCR#86]
Ubuntu 18.04 and Python 3.8.3 (pyenv).

This code:

```
#!/usr/bin/env python3
import easyocr
url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Serif_and_sans-serif_01.svg/320px-Serif_and_sans-serif_01.svg.png'
reader = easyocr.Reader(['en'], gpu=False)
r = reader.readtext(url)
print(r)
```

will generate this error:

```
Using CPU. Note: This module is much faster with a GPU.
Downloading recognition model, please wait
Download complete
Traceback (most recent call last):
  File "./ocr.py", line 6, in <module>
    r = reader.readtext('https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Serif_and_sans-serif_01.svg/320px-Serif_and_sans-serif_01.svg.png')
  File "/home/gslin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/easyocr/easyocr.py", line 225, in readtext
    image_list, max_width = get_image_list(horizontal_list, free_list, img_cv_grey, model_height = imgH)
  File "/home/gslin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/easyocr/utils.py", line 465, in get_image_list
    maximum_y,maximum_x = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by rkcosmos** [comment]
not supported yet. PR welcome.

**Comment by korakot** [comment]
I have sent in a PR for this.

https://github.com/JaidedAI/EasyOCR/pull/104

**Comment by rkcosmos** [comment]
Done by #106
