### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by ftmasadi** [JaidedAI/EasyOCR#869]
Hello
I have a question that unfortunately I could not find the answer to by searching and I hope you can help me.
my question:
When I try to start training with my non-English dataset, I get this error:
`KeyError: Caught KeyError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\range.py", line 385, in get_loc
    return self._range.index(new_key)
ValueError: 111001 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataset.py", line 290, in __getitem__
    return self.dataset[self.indices[idx]]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataset.py", line 235, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "D:\train-error-16 mehr\16-mehr-2\EasyOCR-master\trainer\dataset.py", line 174, in __getitem__
    img_fname = [self.df.at](http://self.df.at/)[index,'filename']
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 2275, in __getitem__
    return super().__getitem__(key)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 2226, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 3622, in _get_value
    row = self.index.get_loc(index)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\range.py", line 387, in get_loc
    raise KeyError(key) from err
KeyError: 111001
 
Thank you for telling me the reason for this error and help me. Thanks`

**Comment by khalilRhouma** [comment]
Hi @ftmasadi, did you find anything about this issue?

**Comment by Bharath314** [comment]
I've run into the same error as well. Have you figured what the issue is? @khalilRhouma

**Comment by Bharath314** [comment]
I ran into this issue whenever `data_filtering_off` is set to True. The code runs without running into this error by changing line 157 in dataset.py to 

```python
self.filtered_index_list = [index for index in range(self.nSamples)]
```

The hypothesis is that that original code ran into an off-by-one index error that can be fixed by the above change.

**Comment by khalilRhouma** [comment]
> I've run into the same error as well. Have you figured what the issue is? [@khalilRhouma](https://github.com/khalilRhouma)

No, I remember that I disabled `data_filtering_off` parameter.

**Comment by Bharath314** [comment]
Thanks for the reply @khalilRhouma ! If still relevant, could you check out my solution and see if it works for you?
