### ISSUE TITLE
size mismatch for Prediction.bias

### ISSUE THREAD

**Issue by thoriumbr** [JaidedAI/EasyOCR#87]
Hi,

trying to run the 3 lines demo, using the git version, and it dies with this error:

```
Traceback (most recent call last):
  File "teste.py", line 2, in <module>
    reader = easyocr.Reader(['pt','en'])
  File "/usr/local/lib/python2.7/dist-packages/easyocr/easyocr.py", line 196, in __init__
    dict_list, MODEL_PATH, device = self.device)
  File "/usr/local/lib/python2.7/dist-packages/easyocr/recognition.py", line 158, in get_recognizer
    model.load_state_dict(new_state_dict)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	size mismatch for Prediction.bias: copying a param with shape torch.Size([168]) from checkpoint, the shape in current model is torch.Size([240]).
	size mismatch for Prediction.weight: copying a param with shape torch.Size([168, 512]) from checkpoint, the shape in current model is torch.Size([240, 512]).
```

Using Python 2.7.12 (default, Apr 15 2020, 17:07:12), on a container running Ubuntu 16.04.6 LTS and host running RHEL 7.7 with kernel 3.10.0-1062.18.1.el7.x86_64.

**Comment by rkcosmos** [comment]
Are you using the last version? Can you try update EasyOCR to version 1.1.3.

**Comment by thoriumbr** [comment]
Downloaded latest version as now (1.1.4), still the same issue

```
Building wheels for collected packages: easyocr
  Building wheel for easyocr (setup.py) ... done
  Created wheel for easyocr: filename=easyocr-1.1.4-py2-none-any.whl size=18039473 sha256=a5ea6e0c040a285453b505d06003f553e0453c413d192ee2c320d840ccc29db5
  Stored in directory: /tmp/pip-ephem-wheel-cache-2g_LRe/wheels/93/58/ba/398b0c76273a01cb9de309eae3a4b4402f5bd58251cd3a0c1e
Successfully built easyocr
Installing collected packages: easyocr
  Attempting uninstall: easyocr
    Found existing installation: easyocr 1.1.3
    Uninstalling easyocr-1.1.3:
      Successfully uninstalled easyocr-1.1.3
Successfully installed easyocr-1.1.4

python test.py 
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    reader = easyocr.Reader(['pt','en'])
  File "/usr/local/lib/python2.7/dist-packages/easyocr/easyocr.py", line 197, in __init__
    dict_list, MODEL_PATH, device = self.device)
  File "/usr/local/lib/python2.7/dist-packages/easyocr/recognition.py", line 158, in get_recognizer
    model.load_state_dict(new_state_dict)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	size mismatch for Prediction.bias: copying a param with shape torch.Size([168]) from checkpoint, the shape in current model is torch.Size([240]).
	size mismatch for Prediction.weight: copying a param with shape torch.Size([168, 512]) from checkpoint, the shape in current model is torch.Size([240, 512]).
```

**Comment by rkcosmos** [comment]
I never had this issue. I'll reopen this and call for help. Maybe someone encounter this before

**Comment by thoriumbr** [comment]
My bad... README.md asks for using pip to install it, easyocr complained about `urllib.request` and one or other lib, I edited the source to use `wget` instead, and `io.open` instead of `open`... Turns out using Python3 solves all the issues...
I would change the README to instruct using `pip3 install easyocr` instead of `pip install easyocr`.
