### ISSUE TITLE
Can't build on M1 macOS Ventura (13.0)

### ISSUE THREAD

**Issue by CaptainStiggz** [JaidedAI/EasyOCR#877]
`pip install easyocr` Fails with `“CMake” is damaged and can’t be opened. You should move it to the Trash.`

```
Building wheels for collected packages: opencv-python-headless
  Building wheel for opencv-python-headless (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for opencv-python-headless (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
        File "/private/var/folders/9l/0lk2nvvs7j39q893l1k0qvcc0000gn/T/pip-build-env-_54wfq8c/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/private/var/folders/9l/0lk2nvvs7j39q893l1k0qvcc0000gn/T/pip-build-env-_54wfq8c/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/private/var/folders/9l/0lk2nvvs7j39q893l1k0qvcc0000gn/T/pip-build-env-_54wfq8c/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):

      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for opencv-python-headless
Failed to build opencv-python-headless
ERROR: Could not build wheels for opencv-python-headless, which is required to install pyproject.toml-based projects
```

```
> cmake --version
cmake version 3.24.2
```

**Comment by u36318** [comment]
Same
