### ISSUE TITLE
error: pyav:  pip install imageio[pyav]

### ISSUE THREAD

**Issue by hktalent** [JaidedAI/EasyOCR#969]
Mac OS
$ py3 -V
Python 3.9.6
easyocr

```
pip list|grep opencv
opencv-contrib-python                             4.5.4.60
opencv-contrib-python-headless                    4.5.4.60
opencv-python                                     4.5.4.60
opencv-python-headless                            4.5.4.60

pip3 list|grep imageio
imageio                                           2.19.2

```
```
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
import requests as requestsSs
import easyocr,urllib3
urllib3.disable_warnings()
requestsSs.packages.urllib3.disable_warnings()

reader = easyocr.Reader(['ch_sim','en'],gpu=False,detector=True,model_storage_directory="/Users/51pwn/MyWork/mybugbounty/ai/modle") # this needs to run only once to load the model into memory
result = reader.readtext('/Users/51pwn/MyWork/mybugbounty/ai/testImg/xx1.jpg', detail=0)
print(result)
```
error
```
py3 chepai.py
Using CPU. Note: This module is much faster with a GPU.
Traceback (most recent call last):
  File "/Users/51pwn/MyWork/mybugbounty/ai/chepai.py", line 28, in <module>
    result = reader.readtext('/Users/51pwn/MyWork/mybugbounty/ai/testImg/xx1.jpg', detail=0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/easyocr/easyocr.py", line 445, in readtext
    img, img_cv_grey = reformat_input(image)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/easyocr/utils.py", line 699, in reformat_input
    img = loadImage(image)  # can accept URL
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/easyocr/imgproc.py", line 12, in loadImage
    img = io.imread(img_file)           # RGB order
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/skimage/io/_io.py", line 53, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/skimage/io/_plugins/imageio_plugin.py", line 15, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/imageio/v2.py", line 200, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/imageio/core/imopen.py", line 303, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `/Users/51pwn/MyWork/mybugbounty/ai/testImg/xx1.jpg`` with iomode `ri`.
Based on the extension, the following plugins might add capable backends:
  pyav:  pip install imageio[pyav]
```

**Comment by worker123187** [comment]
How did you solve it in the end,please?

**Comment by hktalent** [comment]
This module is much faster with a GPU
But I don't have a GPU, so I gave up
